//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyOrbit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalaxyOrbit.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0045GameRes {
            get {
                object obj = ResourceManager.GetObject("_0045GameRes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0045Picres {
            get {
                object obj = ResourceManager.GetObject("_0045Picres", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0058Client {
            get {
                object obj = ResourceManager.GetObject("_0058Client", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0425games_asset {
            get {
                object obj = ResourceManager.GetObject("_0425games_asset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0518map_asset {
            get {
                object obj = ResourceManager.GetObject("_0518map_asset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0628chat_asset {
            get {
                object obj = ResourceManager.GetObject("_0628chat_asset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0630galaxy_asset {
            get {
                object obj = ResourceManager.GetObject("_0630galaxy_asset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _1206Airship {
            get {
                object obj = ResourceManager.GetObject("_1206Airship", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _225afont {
            get {
                object obj = ResourceManager.GetObject("_225afont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _302lottery {
            get {
                object obj = ResourceManager.GetObject("_302lottery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;config&gt;
        ///&lt;resources path=&quot;https://client.guerradenaves.lat/&quot; gMap=&quot;asset/map/&quot; res=&quot;asset/&quot; client=&quot;asset/0058&quot; galaxyAssetPath=&quot;0630galaxy_asset&quot;&gt;
        ///                &lt;resource name=&quot;GameRes&quot;                src=&quot;0045GameRes.swf&quot;  type=&quot;Mc&quot;/&gt;
        ///                &lt;resource name=&quot;games_asset&quot;            src=&quot;0425games_asset.swf&quot;  type=&quot;Mc&quot;/&gt;
        ///                &lt;resource name=&quot;Picres&quot;                 src=&quot;0045Picres.swf&quot;  type=&quot;Mc&quot;/&gt;
        ///                &lt;resource name=&quot;lottery&quot;    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desert_a_00 {
            get {
                object obj = ResourceManager.GetObject("desert_a_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desert_a_01 {
            get {
                object obj = ResourceManager.GetObject("desert_a_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desert_a_02 {
            get {
                object obj = ResourceManager.GetObject("desert_a_02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] desert_a_03 {
            get {
                object obj = ResourceManager.GetObject("desert_a_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;GO2&lt;/title&gt;
        ///	&lt;link rel=&quot;icon&quot; type=&quot;image/ico&quot; href=&quot;favicon.ico&quot; sizes=&quot;32x32&quot; /&gt;
        ///	&lt;style&gt;
        ///		body{
        ///			margin: 0;
        ///		}
        ///        .centerize {
        ///            margin: 0 auto;
        ///            background: black;
        ///            position: relative;
        ///            z-index: 1;
        ///            padding: 0px 0px 0 0px;
        ///            background-size: cover;
        ///            display: flex;
        ///            justify-content: center;
        ///            align-items: center;
        ///            height: 100vh;
        ///        }
        ///
        ///		.full-screen {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] load_a_00 {
            get {
                object obj = ResourceManager.GetObject("load_a_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] load_a_01 {
            get {
                object obj = ResourceManager.GetObject("load_a_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] load_a_02 {
            get {
                object obj = ResourceManager.GetObject("load_a_02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] load_a_03 {
            get {
                object obj = ResourceManager.GetObject("load_a_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*	SWFObject v2.2 &lt;http://code.google.com/p/swfobject/&gt; 
        ///	is released under the MIT License &lt;http://www.opensource.org/licenses/mit-license.php&gt; 
        ///*/
        ///var swfobject = function () { var D = &quot;undefined&quot;, r = &quot;object&quot;, S = &quot;Shockwave Flash&quot;, W = &quot;ShockwaveFlash.ShockwaveFlash&quot;, q = &quot;application/x-shockwave-flash&quot;, R = &quot;SWFObjectExprInst&quot;, x = &quot;onreadystatechange&quot;, O = window, j = document, t = navigator, T = false, U = [h], o = [], N = [], I = [], l, Q, E, B, J = false, a = false, n, G, m = true, M = function [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loader {
            get {
                return ResourceManager.GetString("loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PreLoader {
            get {
                object obj = ResourceManager.GetObject("PreLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] preloader_asset {
            get {
                object obj = ResourceManager.GetObject("preloader_asset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snow_a_00 {
            get {
                object obj = ResourceManager.GetObject("snow_a_00", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snow_a_01 {
            get {
                object obj = ResourceManager.GetObject("snow_a_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snow_a_02 {
            get {
                object obj = ResourceManager.GetObject("snow_a_02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snow_a_03 {
            get {
                object obj = ResourceManager.GetObject("snow_a_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
